---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	llm_call_answer(llm_call_answer)
	llm_call_refine_query(llm_call_refine_query)
	validate_response(validate_response)
	aggregator(aggregator)
	references_generator(references_generator)
	__end__([<p>__end__</p>]):::last
	__start__ --> llm_call_refine_query;
	llm_call_answer --> validate_response;
	llm_call_refine_query --> llm_call_answer;
	references_generator --> aggregator;
	validate_response -. &nbsp;Accepted&nbsp; .-> aggregator;
	validate_response --> references_generator;
	aggregator --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
