---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	maybe_use_related_q(maybe_use_related_q)
	orchestrator(orchestrator)
	query_grounded(query_grounded)
	synthesizer(synthesizer)
	emit_query_answer_references(emit_query_answer_references)
	related_queries_and_categories(related_queries_and_categories)
	__end__([<p>__end__</p>]):::last
	__start__ --> maybe_use_related_q;
	emit_query_answer_references --> related_queries_and_categories;
	maybe_use_related_q -. &nbsp;full&nbsp; .-> orchestrator;
	maybe_use_related_q -. &nbsp;related_only&nbsp; .-> related_queries_and_categories;
	orchestrator -.-> query_grounded;
	query_grounded --> synthesizer;
	synthesizer --> emit_query_answer_references;
	related_queries_and_categories --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
