---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	analyze_query(analyze_query)
	fast_single(fast_single)
	query_grounded(query_grounded)
	synthesize_style_stream(synthesize_style_stream)
	emit_query_answer_references(emit_query_answer_references)
	related_queries_dialog_from_query(related_queries_dialog_from_query)
	refuse_harm_to_others(refuse_harm_to_others)
	help_after_harm(help_after_harm)
	address_prejudice(address_prejudice)
	respond_self_harm(respond_self_harm)
	__end__([<p>__end__</p>]):::last
	__start__ --> analyze_query;
	address_prejudice --> emit_query_answer_references;
	analyze_query -.-> address_prejudice;
	analyze_query -.-> fast_single;
	analyze_query -.-> help_after_harm;
	analyze_query -.-> query_grounded;
	analyze_query -.-> refuse_harm_to_others;
	analyze_query -.-> respond_self_harm;
	emit_query_answer_references --> related_queries_dialog_from_query;
	fast_single --> synthesize_style_stream;
	help_after_harm --> emit_query_answer_references;
	query_grounded --> synthesize_style_stream;
	refuse_harm_to_others --> emit_query_answer_references;
	respond_self_harm --> emit_query_answer_references;
	synthesize_style_stream --> emit_query_answer_references;
	related_queries_dialog_from_query --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
