---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>Start</p>]):::first
	analyze_query["Analyser spørsmål"]
	fast_single["Hurtigsvar (enkelt)"]
	query_grounded["Kunnskapsbasert svar"]
	synthesize_style_stream["Formuler &amp; strøm svar"]
	emit_query_answer_references["Send svar + kilder"]
	related_queries_dialog_from_query["Relaterte spørsmål"]
	refuse_harm_to_others["Avvis: skade på andre"]
	help_after_harm["Hjelp etter skade"]
	address_prejudice["Adresser fordommer"]
	__end__([<p>Slutt</p>]):::last
	__start__ --> analyze_query;
	address_prejudice --> emit_query_answer_references;
	analyze_query -.-> address_prejudice;
	analyze_query -.-> fast_single;
	analyze_query -.-> help_after_harm;
	analyze_query -.-> query_grounded;
	analyze_query -.-> refuse_harm_to_others;
	emit_query_answer_references --> related_queries_dialog_from_query;
	fast_single --> synthesize_style_stream;
	help_after_harm --> emit_query_answer_references;
	query_grounded --> synthesize_style_stream;
	refuse_harm_to_others --> emit_query_answer_references;
	synthesize_style_stream --> emit_query_answer_references;
	related_queries_dialog_from_query --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
